export const ENDPOINT = {
  home: "/",
  login: "/account/sign-in",
  eyeglasses: "/eyeglasses",
  sunglasses: "/sunglasses",
  contactUs: "/help/contact-us",
  faq: "/help/faq",
  eyeCare: "/eye-care",
  contactLenses: "/contact-lenses",
  measurePdActions: "/resources/measure-pupil-distance",
  onlineVision: "/account/online-vision-test-purchases",
  onlineVisionTestIntroduction: "/online-vision-test",
  adminPanel: "/admin-manage",
  checkout: "/checkout",
  deals: "/eyewear/deals",
  accountMain: "/account/main",
  eqPoints: "/account/ezpoints",
  wishlist: "/account/wishlist",
};
